FROM node:22-alpine AS build_stage

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV:-production}

RUN npm install -g pnpm vite

WORKDIR /app

COPY ./frontend .

RUN pnpm install --frozen-lockfile

RUN pnpm build

FROM nginx:alpine

COPY --from=build_stage /app/dist /usr/share/nginx/html

COPY ./infra/node/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
