FROM python:3.12-slim

ARG APP_PORT=3000

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install gunicorn && \
    pip install --no-cache-dir -r requirements.txt
# hardcode port
# CMD ["gunicorn", "--bind", "0.0.0.0:3000", "main:app"]

# dinamyc port
CMD ["sh", "-c", "exec gunicorn --bind 0.0.0.0:$APP_PORT main:app"]