FROM node:20-alpine AS build

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

#EXPOSE 5173

# CMD ["pnpm", "run", "dev", "--host"]

RUN pnpm run build

EXPOSE 4173

CMD ["pnpm", "run", "preview", "--host"]

